name = "grunglebird"
compatibility_date = "2025-04-01"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "grunglebird-db"
database_id = "145f538f-f9b9-4d39-8911-bd8eb0b6c779"
migrations_dir = "migrations"
