name = "grunglebird"
main = "@astrojs/cloudflare/entrypoints/server"
compatibility_date = "2026-05-21"

[assets]
binding = "ASSETS"
directory = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "grunglebird-db"
database_id = "145f538f-f9b9-4d39-8911-bd8eb0b6c779"
migrations_dir = "migrations"
